version: "3.9"

services:
  rest_tour:
    build: .
    container_name: rest_tour_bot
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./admin_panel/static:/app/admin_panel/static
      - ./admin_panel/templates:/app/admin_panel/templates
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
