version: "3.9"

services:
  rest_tour:
    build: .
    container_name: rest_tour_bot
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
